#!/usr/bin/python3
import sys
import subprocess
hint_proc = subprocess.run(["jshint", "."])
if hint_proc.returncode != 0:
    print("Linting failed. Commit aborted")
    sys.exit(1)
print("Commit accepted")
sys.exit(0)